[package]
name = "bandit"
version = "0.11.1"
authors = ["Michael Bohn <michael.bohn@freiheit.com>"]
description = "Bandit Algorithms in Rust"
license = "GPL-3.0"
repository = "https://github.com/Ragnaroek/bandit"

[dependencies]
rand = "0.4.1"
serde = "1.0.27"
serde_json = "1.0.9"
serde_derive = "1.0.27"

[dev-dependencies]
regex = "0.2"
