[package]
name = "bandit"
version = "0.12.2"
authors = ["Michael Bohn <michael.bohn@freiheit.com>"]
description = "Bandit Algorithms in Rust"
license = "GPL-3.0"
repository = "https://github.com/Ragnaroek/bandit"

[dependencies]
rand = "0.7.3"
serde = "1.0.114"
serde_json = "1.0.56"
serde_derive = "1.0.114"

[dev-dependencies]
regex = "1.3.9"
